### ISSUE TITLE
Travis failing for 2.7?

### ISSUE THREAD

**Issue by e-koch** [e-koch/FilFinder#12]
Not sure where this is coming from, since I haven't changed any of that code. Maybe a change in numpy?

```
Traceback (most recent call last):
  File "/home/travis/build/e-koch/FilFinder/fil_finder/tests/test_whole.py", line 63, in test_without_rht_branches
    test2.find_widths()
  File "/home/travis/build/e-koch/FilFinder/fil_finder/filfind_class.py", line 926, in find_widths
    self.array_offsets[n], self.imgscale)
  File "/home/travis/build/e-koch/FilFinder/fil_finder/width.py", line 454, in radial_profile
    range(1, int(nbins) + 1)])
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3084, in median
    overwrite_input=overwrite_input)
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2997, in _ureduce
    r = func(a, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/numpy/lib/function_base.py", line 3138, in _median
    n = np.isnan(part[..., -1])
IndexError: index -1 is out of bounds for axis 0 with size 0
```

**Comment by e-koch** [comment]
Addressed in #13
