### ISSUE TITLE
errors using Plummer1D as fit_model for find_widths

### ISSUE THREAD

**Issue by manferna** [e-koch/FilFinder#76]
if you pass the Plummer1D model from Radfil to  find_widths, there is the need, close to line 978 in filament.py, to declare the variable found_width, and set idx (for the Plummer1D it will be idx=2.

With this fixed in my PC's version of the code, I'm getting an error when issuing a width_fits call after find_widths; could it be because I'm getting some nan values in the widths?:  

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/astropy/table/operations.py", line 1309, in _vstack
    col = col_cls.info.new_like(cols, n_rows, metadata_conflicts, out_name)
  File "/usr/local/lib/python3.8/dist-packages/astropy/table/column.py", line 326, in new_like
    attrs = self.merge_cols_attributes(cols, metadata_conflicts, name,
  File "/usr/local/lib/python3.8/dist-packages/astropy/utils/data_info.py", line 713, in merge_cols_attributes
    out['dtype'] = metadata.common_dtype(cols)
  File "/usr/local/lib/python3.8/dist-packages/astropy/utils/metadata.py", line 64, in common_dtype
    raise tme
astropy.utils.metadata.MergeConflictError: Arrays have incompatible types ['object', 'str256']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "filfinder2d.py", line 73, in <module>
    tmp_table = fil.width_fits(xunit=u.pc)
  File "/home/manferna/.local/lib/python3.8/site-packages/fil_finder/filfinder2D.py", line 1037, in width_fits
    tab = tab_vstack([tab, add_tab])
  File "/usr/local/lib/python3.8/dist-packages/astropy/table/operations.py", line 643, in vstack
    out = _vstack(tables, join_type, col_name_map, metadata_conflicts)
  File "/usr/local/lib/python3.8/dist-packages/astropy/table/operations.py", line 1313, in _vstack
    raise TableMergeError("The '{}' columns have incompatible types: {}"
astropy.table.np_utils.TableMergeError: The 'model_type' columns have incompatible types: ['object', 'str256']

**Comment by e-koch** [comment]
Thanks @manferna! This is now fixed in the main branch from #75
