### ISSUE TITLE
fil.analyze_skeletons not working in example files

### ISSUE THREAD

**Issue by teogeo1996** [e-koch/FilFinder#85]
I am trying to run the example files. I have stumbled across an issue with fil.analyze skeletons. I am following the example steps exactly but when I get to the point of 
fil.analyze_skeletons()
plt.imshow(fil.skeleton, origin='lower')

I get an error saying: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/c21094896/FilFinder/fil_finder/filfinder2D.py", line 665, in analyze_skeletons
    fil.skeleton_analysis(self.image, verbose=verbose,
  File "/Users/c21094896/FilFinder/fil_finder/filament.py", line 277, in skeleton_analysis
    prune_graph(G, nodes, edge_list, max_path, labeled_mask,
  File "/Users/c21094896/FilFinder/fil_finder/length.py", line 662, in prune_graph
    G[n] = merge_nodes(node, G[n])
NameError: name 'merge_nodes' is not defined

Is there an easy fix to that?

**Comment by e-koch** [comment]
My apologies for missing this issue, @teogeo1996 . Are you still encountering this issue? `merge_nodes` is an internal function so this seems like it might be an installation issue.

Can you try the new v1.8 release and see if it's fixed with the new version?
